POST http://localhost:8080/scouts
Content-Type: application/json

{
  "name" : "jenicek",
  "dateOfBirth" : "4.11.2000"
}

###
GET http://localhost:8080/scouts

###
GET http://localhost:8080/scouts/20

###
PUT http://localhost:8080/scouts/20/unit
Content-Type: application/json

{
  "number" : 98
}


###
GET http://localhost:8080/units/98/scouts

###
DELETE http://localhost:8080/scouts/3/unit

###
PUT http://localhost:8080/scouts/8
Content-Type: application/json

{
  "name" : "jenik",
  "trips" : [{"id" :  1}]
}

###
DELETE http://localhost:8080/scouts/18

###
POST http://localhost:8080/units
Content-Type: application/json

{
  "number" : 97
}

###
POST http://localhost:8080/units/97/scouts
Content-Type: application/json

{
  "id" : 3,
  "name" : "pepicek"
}

###
GET http://localhost:8080/units

###
GET http://localhost:8080/units/97

###
GET http://localhost:8080/units/by?location=praha

###
PUT http://localhost:8080/units/97
Content-Type: application/json

{
  "location" : "praha"
}

###
POST http://localhost:8080/trips
Content-Type: application/json

{
  "destination" : "Brno",
  "participants" : [{
    "id" : 1
  }]
}

###
GET http://localhost:8080/trips

###
GET http://localhost:8080/trips/19/scouts/

###
GET http://localhost:8080/trips/19

###
POST http://localhost:8080/scouts/18/trips
Content-Type: application/json

{
  "id" : 19
}
###
DELETE http://localhost:8080/scouts/18/trips/19